platform :ios, '13.0'

target 'Flash Chat iOS13' do
  use_frameworks!

  # Pods for Flash Chat iOS13
  pod 'CLTypingLabel', '~> 0.4.0'

  # add pods for desired Firebase products
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
end
